spring.application.name=localbasket-backend

# ==========================
# Database Configuration
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3306/localbasket_db
spring.datasource.username=root
spring.datasource.password=Ramya@sweety1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# JPA / Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Show SQL queries
logging.level.org.hibernate.SQL=DEBUG

# Show query parameter values
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Show Spring Data JPA queries
logging.level.org.springframework.data.jpa=DEBUG

jwt.secret=ThisIsMyVerySecretKeyForLocalBasketApplication123456789
jwt.expiration=86400000

# ==========================
# Server
# ==========================
server.port=8080